'use client';

import { useState, useEffect, useRef } from 'react';
import { Check, X, ShoppingCart, Package, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { toast } from 'sonner';
import { useStore } from '@/lib/store';
import { simpleNormalize } from '@/lib/canonicalize';
import type { SavedRecipe, RecipeIngredient } from '@/lib/types';

interface PantryItem {
  id: string;
  name: string;
  genericName: string | null;
  category: string | null;
  isRunningLow: boolean;
}

interface ShoppingList {
  id: string;
  name: string;
}

interface RecipePantryIntegrationProps {
  recipe: SavedRecipe;
}

// =============================================================================
// MATCHING — now trivial because both sides use Gemini canonical names
// =============================================================================
//
// How it works:
//   1. Pantry items already have a `genericName` generated by Gemini (via /api/pantry).
//   2. Recipe ingredients get a `canonicalName` generated by Gemini (via /api/canonicalize),
//      lazily on first load and cached in the recipe's DB record.
//   3. Matching = compare canonical names with prefix matching for specificity.
//
// Example:
//   Recipe: "Crushed red pepper" → canonicalName: "red pepper flakes"
//   Pantry: "Chilli Flakes" → genericName: "red pepper flakes"
//   → MATCH (exact canonical name match)
//
//   Recipe: "Chicken breast" → canonicalName: "chicken breast"
//   Pantry: "Chicken Breast Tenders" → genericName: "chicken breast"
//   → MATCH (exact canonical name match)
//
//   Recipe: "Olive oil" → canonicalName: "olive oil"
//   Pantry: "Vegetable oil" → genericName: "vegetable oil"
//   → NO MATCH (different canonical names)

function isIngredientMatch(
  recipeCanonical: string,
  pantryGeneric: string,
): boolean {
  if (!recipeCanonical || !pantryGeneric) return false;

  // 1. Exact match (most common case after canonicalization).
  if (recipeCanonical === pantryGeneric) return true;

  // 2. Prefix match — one is a prefix of the other.
  //    Handles cases where the recipe is more specific or less specific than the pantry item.
  //    e.g. recipe "chicken" matches pantry "chicken breast" (recipe is generic, pantry is specific)
  //    e.g. recipe "chicken breast" matches pantry "chicken" (recipe is specific, pantry is generic)
  //    BUT "olive oil" does NOT prefix-match "vegetable oil" — they're different.
  if (pantryGeneric.startsWith(recipeCanonical + ' ') ||
      recipeCanonical.startsWith(pantryGeneric + ' ')) {
    return true;
  }

  return false;
}

// =============================================================================
// COMPONENT
// =============================================================================

export function RecipePantryIntegration({ recipe }: RecipePantryIntegrationProps) {
  const [shoppingLists, setShoppingLists] = useState<ShoppingList[]>([]);
  const [loading, setLoading] = useState(true);
  const [canonicalizing, setCanonicalizing] = useState(false);
  const [selectedListId, setSelectedListId] = useState<string>('');
  const [adding, setAdding] = useState(false);
  const [canonicalizedIngredients, setCanonicalizedIngredients] = useState<RecipeIngredient[]>([]);
  const { authToken, pantryItems, fetchPantry } = useStore();
  const hasCanonicalized = useRef(false);

  useEffect(() => {
    async function loadData() {
      try {
        // Pantry items come from the store (cached for route switching).
        if (pantryItems.length === 0) {
          await fetchPantry();
        }

        const listsRes = await fetch('/api/shopping-lists', {
          headers: authToken ? { Authorization: `Bearer ${authToken}` } : {},
        });
        const listsData = await listsRes.json();
        setShoppingLists(listsData.lists || []);
        if (listsData.lists?.length > 0) {
          setSelectedListId(listsData.lists[0].id);
        }
      } catch {
        // Silent fail — pantry integration is optional.
      } finally {
        setLoading(false);
      }
    }
    loadData();
  }, [authToken, pantryItems.length, fetchPantry]);

  // ---- Lazy canonicalization of recipe ingredients ----
  // If the recipe ingredients don't have canonicalName yet, call the
  // /api/canonicalize endpoint to get them, then update the recipe in the DB
  // so it's a one-time cost.
  useEffect(() => {
    if (hasCanonicalized.current) return;
    if (!recipe.ingredients || recipe.ingredients.length === 0) return;

    const needsCanonicalization = recipe.ingredients.some(
      (ing) => !ing.canonicalName,
    );

    if (!needsCanonicalization) {
      setCanonicalizedIngredients(recipe.ingredients);
      hasCanonicalized.current = true;
      return;
    }

    hasCanonicalized.current = true;
    setCanonicalizing(true);

    async function canonicalize() {
      try {
        const names = recipe.ingredients.map((ing) => ing.name);
        const res = await fetch('/api/canonicalize', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ names }),
        });

        if (!res.ok) throw new Error('Canonicalization failed');

        const data = await res.json();
        const canonicalMap: Record<string, string> = data.canonical || {};

        const updated = recipe.ingredients.map((ing) => ({
          ...ing,
          canonicalName: canonicalMap[ing.name] || simpleNormalize(ing.name),
        }));

        setCanonicalizedIngredients(updated);

        // Update the recipe in the DB so we don't canonicalize again.
        // Use the private API if we have a token, otherwise skip (public view).
        if (authToken && !recipe.id.startsWith('temp-')) {
          fetch(`/api/recipes/${recipe.id}`, {
            method: 'PUT',
            headers: {
              'Content-Type': 'application/json',
              Authorization: `Bearer ${authToken}`,
            },
            body: JSON.stringify({ ingredients: updated }),
          }).catch(() => {
            // Silent fail — the canonical names are still used in-memory.
          });
        }
      } catch {
        // Fallback: use simple client-side normalization.
        const fallback = recipe.ingredients.map((ing) => ({
          ...ing,
          canonicalName: simpleNormalize(ing.name),
        }));
        setCanonicalizedIngredients(fallback);
      } finally {
        setCanonicalizing(false);
      }
    }

    canonicalize();
  }, [recipe, authToken]);

  // Ingredients that are truly free — you don't have to buy them.
  const PANTRY_STAPLES = ['water'];

  // Match recipe ingredients against pantry items.
  const ingredients = canonicalizedIngredients.length > 0
    ? canonicalizedIngredients
    : recipe.ingredients || [];

  const ingredientStatus = ingredients.map((ing, idx) => {
    const ingNameLower = ing.name.toLowerCase().trim();
    const isStaple = PANTRY_STAPLES.some(
      (s) => ingNameLower === s || ingNameLower.startsWith(s + ' '),
    );

    if (isStaple) {
      return { idx, ingredient: ing, inPantry: true, pantryItem: null, isStaple: true };
    }

    // Get the canonical name (from Gemini if available, else simple normalize).
    const recipeCanonical = ing.canonicalName || simpleNormalize(ing.name);

    const match = pantryItems.find((p) => {
      const pantryGeneric = p.genericName || simpleNormalize(p.name);
      return isIngredientMatch(recipeCanonical, pantryGeneric);
    });

    return {
      idx,
      ingredient: ing,
      inPantry: !!match,
      pantryItem: match,
      isStaple: false,
    };
  });

  const haveCount = ingredientStatus.filter((s) => s.inPantry).length;
  const missingIngredients = ingredientStatus
    .filter((s) => !s.inPantry && !s.isStaple)
    .map((s) => s.ingredient);
  const missingCount = missingIngredients.length;

  async function addMissingToShoppingList() {
    if (!selectedListId || missingIngredients.length === 0) return;
    setAdding(true);

    try {
      const items = missingIngredients.map((ing) => ({
        name: ing.name,
        genericName: ing.canonicalName || simpleNormalize(ing.name),
        quantity: ing.amount ? `${ing.amount}${ing.unit ? ' ' + ing.unit : ''}` : undefined,
        recipeId: recipe.id,
      }));

      const res = await fetch(`/api/shopping-lists/${selectedListId}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(authToken ? { Authorization: `Bearer ${authToken}` } : {}),
        },
        body: JSON.stringify(items),
      });

      if (!res.ok) throw new Error('Failed to add items.');
      toast.success(
        `${missingIngredients.length} item${missingIngredients.length > 1 ? 's' : ''} added to shopping list.`,
      );
    } catch {
      toast.error('Could not add items to shopping list.');
    } finally {
      setAdding(false);
    }
  }

  if (loading || canonicalizing) {
    return (
      <Card>
        <CardContent className="py-4">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Loader2 className="h-4 w-4 animate-spin" />
            {canonicalizing ? 'Canonicalizing ingredients...' : 'Checking pantry...'}
          </div>
        </CardContent>
      </Card>
    );
  }

  if (pantryItems.length === 0) {
    return null;
  }

  return (
    <Card>
      <CardContent className="py-4 space-y-3">
        {/* Summary */}
        <div className="flex items-center justify-between gap-2 flex-wrap">
          <div className="flex items-center gap-2">
            <Package className="h-4 w-4 text-primary" />
            <span className="text-sm font-medium">Pantry Check</span>
          </div>
          <div className="flex items-center gap-2">
            {haveCount > 0 && (
              <Badge variant="secondary" className="text-xs gap-1">
                <Check className="h-3 w-3 text-green-500" />
                {haveCount} have
              </Badge>
            )}
            {missingCount > 0 && (
              <Badge variant="outline" className="text-xs gap-1 text-amber-600 border-amber-300">
                <X className="h-3 w-3" />
                {missingCount} missing
              </Badge>
            )}
            {missingCount === 0 && haveCount > 0 && (
              <Badge variant="secondary" className="text-xs gap-1 text-green-600">
                <Check className="h-3 w-3" />
                All ingredients!
              </Badge>
            )}
          </div>
        </div>

        {/* Ingredient list with status */}
        <div className="space-y-1">
          {ingredientStatus.map(({ idx, ingredient, inPantry, pantryItem }) => (
            <div key={idx} className="flex items-center gap-2 text-sm py-1">
              {inPantry ? (
                <Check className="h-3.5 w-3.5 text-green-500 shrink-0" />
              ) : (
                <X className="h-3.5 w-3.5 text-amber-500 shrink-0" />
              )}
              <span className={inPantry ? 'text-muted-foreground line-through' : ''}>
                {ingredient.name}
              </span>
              {(ingredient.amount || ingredient.unit) && (
                <span className="text-xs text-muted-foreground">
                  {ingredient.amount}
                  {ingredient.unit && ` ${ingredient.unit}`}
                </span>
              )}
              {inPantry && pantryItem?.isRunningLow && (
                <Badge variant="outline" className="text-xs text-amber-600 border-amber-300">
                  Low
                </Badge>
              )}
            </div>
          ))}
        </div>

        {/* Add missing to shopping list */}
        {missingCount > 0 && shoppingLists.length > 0 && (
          <div className="flex items-center gap-2 pt-2 border-t border-border/40">
            <Select value={selectedListId} onValueChange={setSelectedListId}>
              <SelectTrigger className="h-8 text-xs flex-1">
                <SelectValue placeholder="Select list..." />
              </SelectTrigger>
              <SelectContent>
                {shoppingLists.map((list) => (
                  <SelectItem key={list.id} value={list.id} className="text-xs">
                    {list.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Button
              size="sm"
              onClick={addMissingToShoppingList}
              disabled={adding || !selectedListId}
              className="h-8 gap-1.5 text-xs"
            >
              {adding ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
              ) : (
                <ShoppingCart className="h-3.5 w-3.5" />
              )}
              Add {missingCount} missing
            </Button>
          </div>
        )}

        {missingCount > 0 && shoppingLists.length === 0 && (
          <p className="text-xs text-muted-foreground pt-2 border-t border-border/40">
            Create a shopping list first to add missing ingredients.
          </p>
        )}
      </CardContent>
    </Card>
  );
}
